config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    validates :title, presence: true
    validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# This is a basic HomeController with an index that does one thig: render 
# the view file associated with the controller action

class HomeController < ApplicationController
    def index
        render
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<style>
/* beginning of styling classes for introduction */
.headingstyle{
  text-align: center;
  font-size: 16 px;
  color: #303030;
  font-family:Verdana, sans-serif;
  
}

.paragraphstyle{
  font-size: 13 px;
  color: #303030;
  font-family:Verdana, sans-serif;
}

tab1 { padding-left: 4em; }
/* end of styling classes for introduction */

</style>
</head>

<html lang="en">
  <head> #heading of the website
    <meta charset="UTF-8"> #utf 8 styling to fit all kinds of devices
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> #also used to fit all kinds of devices
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> #choosing which web browser will be preferred/acceptable
    <title>CS3300 Portfolio Project</title>

  </head>
  
  <body>
    <div style="margin: 5% 0 0 10%;"> #create a margin using percentages of the screen
    <h1>Projects</h1>    #project heading
    <h1>CS 3300 Portfolio Project - Fall 2022</h1> #details which project we are working with

      <div style="padding-left: 2rem;"> #little padding on the display to move it over
        <h4 style="color: blue"> Emily Ng </h4>  #using CSS to make my name blue and HTML to make my name a heading
        

        <!--- Explain what the block of code below this line is doing --->

        <% if user_signed_in? %> #if the user is able to sign in 
          
          <div> Welcome <%= current_user.email %> </div> #display welcome and the user's email in it's own bottstrap divider
          <%= button_to "Sign out", destroy_user_session_path, method: :delete %> #can use sign out button to render the paths only accessible to the user inaccessible
        
        <% else %>
          <a href="/users/sign_in"> Sign in</a> #otherwise, prompt the user with  a sign in link that will lead to a sign in page
        <% end %>

        #add a comment
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300Iteration04</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <!--- <p class="notice"><%= notice %></p> --->
  <!--- <p class="alert"><%= alert %></p> --->
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<style>
/* beginning of styling classes for introduction */
.headingstyle{
  text-align: center;
  font-size: 16 px;
  color: #303030;
  font-family:Verdana, sans-serif;
  
}

.paragraphstyle{
  text-align:left;
  font-size: 13 px;
  color: #303030;
  font-family:Verdana, sans-serif;
}

tab1 { padding-left: 4em; }
/* end of styling classes for introduction */

</style>
</head>
</style>

<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
<a style="font-family: 'Verdana', sans-serif;"> <%= form.label :title %> </a>
<%= form.text_field :title, :class => 'form-control' %>
</div>

<div class="field">
<a style="font-family: 'Verdana', sans-serif;"> <%= form.label :description %> </a>
<%= form.text_area :description, :class => 'form-control' %>
</div>

<div class="container-fluid-nav text-center mt-4">
 <%= form.submit :class => 'btn btn-outline-primary' %>
</div>
<% end %>

app/views/projects/_project.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<style>
/* beginning of styling classes for introduction */
.headingstyle{
  text-align: center;
  font-size: 16 px;
  color: #303030;
  font-family:Verdana, sans-serif;
  
}

.paragraphstyle{
  text-align:left;
  font-size: 13 px;
  color: #303030;
  font-family:Verdana, sans-serif;
}

tab1 { padding-left: 4em; }
/* end of styling classes for introduction */

</style>
</head>
</style>

<div id="<%= dom_id project %>">
  
    <h3>
      <%= project.title %>
    </h3> 

 

  <p>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<style>
/* beginning of styling classes for introduction */
.headingstyle{
  text-align: center;
  font-size: 16 px;
  color: #303030;
  font-family:Verdana, sans-serif;
  
}

.paragraphstyle{
  font-size: 13 px;
  color: #303030;
  font-family:Verdana, sans-serif;
}

tab1 { padding-left: 4em; }
/* end of styling classes for introduction */

</style>
</head>
<body>
<!-- Top navigation bar --->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/users/sign_in">Sign in</a>
          <a class="dropdown-item" href="/users/sign_up">Sign up</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

<!--- Intro name and paragraph --->
<div class="container">
<h1 class = "headingstyle"> Emily Ng </h1>
<p class = "paragraphstyle">
  <tab1>Determined, detail-oriented, and adaptable <a target = "_blank" title = "More about the degree" href ="https://eas.uccs.edu/cs/academics/graduate-programs/master-of-science-in-computer-science" style = "color: bluegray">Masters of Science in Computer Science </a> student passionate about coding, data science, and game theory. </tab1> 
  Experienced in computational mathematical economics through both theoretical and practical applications of game theory, probability theory, economic theory, socioeconomic theory, and advanced statistical modeling. 
  Worked in community engagement, journalism, and on various teams. 
  Honed verbal and written communication skills as a multimedia journalist at The Colorado College Catalyst, The Colorado Springs Independent, and KKTV News.
</p>
</div>

<!--- special skills section using columns and lists --->
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h6><tab1> Programming Languages </tab1></h6>
      <ul style="list-style-type:circle""color: #303030"
      "font-family:Verdana, sans-serif">
      <li> Java </li>
      <li> C </li>
      <li> Bash</li>
      <li> Python </li>
      <li> Ruby </li>
      <li> R </li>
      <li> STATA </li>
      </ul>
    </div>
    <div class="col-sm-4">
      <h6><tab1>Technical Skills</tab1></h6>
      <ul style="list-style-type:circle""color: #303030"
      "font-family:Verdana, sans-serif" "font-size: 10px">
      <li> Agile proccess development </li>
      <li> Executed software development and the usage of software development tools</li>
      <li> Fluent in Object-oriented programming</li>
      <li> Experienced in Procedural Programming </li>
      <li> Skilled in using debuggers, editors and file systems </li>
      <li> Understood and Implemented dynamic memory allocation </li>
      <li> Well-versed in data analysis</li>
      </ul>
    </div>
    <div class="col-sm-4">
      <h6><tab1>Soft Skills</tab1></h6>        
      <ul style="list-style-type:circle""color: #303030"
      "font-family:Verdana, sans-serif">
      <li> Adaptibility/Flexibility </li>
      <li> Teamwork/Collaboration </li>
      <li> Communication </li>
      <li> Problem Solving </li>
      <li> Critical Thinking </li>
      <li> Leadership </li>
      <li> Decisiveness </li>
      </ul>
    </div>
  </div>
</div>

<!---Displaying all projects --->
<div class="container">
  <div class="row">
    <div class="col">
    <div id="projects">
  <% @projects.each do |project| %>
    
    <div class="card", style="margin: 1rem;">
    <%= render project %>
    <a>
      <%= link_to "Show this project", project, class: "btn btn-primary"%>
    </a>
</div>
    </div>
  <% end %>
  <%= link_to "New project", new_project_path %>
</div>

      
    </div>
    
</div>

</body>
</html>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<style>
/* beginning of styling classes for introduction */
.headingstyle{
  text-align: center;
  font-size: 16 px;
  color: #303030;
  font-family:Verdana, sans-serif;
  
}

.paragraphstyle{
  text-align:left;
  font-size: 13 px;
  color: #303030;
  font-family:Verdana, sans-serif;
}

tab1 { padding-left: 4em; }
/* end of styling classes for introduction */

</style>
</head>
</style>

<p style="color: green"> <%= notice %> </p>
<h1 class= "headingstyle">
<strong><%= @project.title %> </strong>
</h1>

<p class="paragraphstyle">
<tab1><%= @project.description %>
</p>

<div class="card", style="margin: 1rem;">
    <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-outline-primary"%>
    <br>
    <%= link_to "Back to projects", projects_path, class: "btn btn-outline-danger"%>
    <br>
    <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-outline-warning btn-block" %>
  
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>